// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhaJ0vxlg8DmUatnrZmqBCnyifYHr3Fdk',
    appId: '1:806437424443:web:d9973457a4f9a54435bb1e',
    messagingSenderId: '806437424443',
    projectId: 'marketplace-secondhand',
    authDomain: 'marketplace-secondhand.firebaseapp.com',
    storageBucket: 'marketplace-secondhand.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5iarmestVybRFPtDER0Mq_K8uroLSxFM',
    appId: '1:806437424443:android:aa78c58766f98c7335bb1e',
    messagingSenderId: '806437424443',
    projectId: 'marketplace-secondhand',
    storageBucket: 'marketplace-secondhand.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMht6mQjyx7G-XmW3YYNDBPjtR9OQAxNk',
    appId: '1:806437424443:ios:cf24417f5881a64635bb1e',
    messagingSenderId: '806437424443',
    projectId: 'marketplace-secondhand',
    storageBucket: 'marketplace-secondhand.firebasestorage.app',
    iosBundleId: 'com.secondhand.marketplace.secondhandMarketplace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMht6mQjyx7G-XmW3YYNDBPjtR9OQAxNk',
    appId: '1:806437424443:ios:cf24417f5881a64635bb1e',
    messagingSenderId: '806437424443',
    projectId: 'marketplace-secondhand',
    storageBucket: 'marketplace-secondhand.firebasestorage.app',
    iosBundleId: 'com.secondhand.marketplace.secondhandMarketplace',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhaJ0vxlg8DmUatnrZmqBCnyifYHr3Fdk',
    appId: '1:806437424443:web:2135cd4f3db3c76935bb1e',
    messagingSenderId: '806437424443',
    projectId: 'marketplace-secondhand',
    authDomain: 'marketplace-secondhand.firebaseapp.com',
    storageBucket: 'marketplace-secondhand.firebasestorage.app',
  );
}
